import { Document, Page, Text, View, StyleSheet, PDFDownloadLink } from '@react-pdf/renderer';
import { Button } from '@/components/ui/button';
import { Download } from 'lucide-react';
import { format } from 'date-fns';

const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontSize: 10,
    fontFamily: 'Helvetica',
  },
  header: {
    marginBottom: 20,
    borderBottomWidth: 2,
    borderBottomColor: '#2563eb',
    paddingBottom: 10,
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#1f2937',
  },
  subtitle: {
    fontSize: 12,
    color: '#6b7280',
    marginTop: 4,
  },
  section: {
    marginBottom: 20,
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#2563eb',
    marginBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#e5e7eb',
    paddingBottom: 4,
  },
  statsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  statCard: {
    width: '48%',
    padding: 15,
    backgroundColor: '#f9fafb',
    borderRadius: 8,
    marginBottom: 10,
  },
  statLabel: {
    fontSize: 10,
    color: '#6b7280',
    marginBottom: 4,
  },
  statValue: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#1f2937',
  },
  table: {
    marginTop: 10,
  },
  tableHeader: {
    flexDirection: 'row',
    backgroundColor: '#2563eb',
    padding: 8,
    color: 'white',
  },
  tableRow: {
    flexDirection: 'row',
    padding: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#e5e7eb',
  },
  tableCell: {
    flex: 1,
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 40,
    right: 40,
    textAlign: 'center',
    color: '#9ca3af',
    fontSize: 8,
    borderTopWidth: 1,
    borderTopColor: '#e5e7eb',
    paddingTop: 10,
  },
});

interface DashboardPDFProps {
  stats: {
    todaySales: number;
    todayRevenue: number;
    lowStockItems: number;
    expiringItems: number;
  };
  recentSales: Array<{
    invoice_number: string;
    patient_name: string;
    total: number;
    created_at: string;
  }>;
  shopName?: string;
}

const DashboardDocument = ({ stats, recentSales, shopName }: DashboardPDFProps) => (
  <Document>
    <Page size="A4" style={styles.page}>
      <View style={styles.header}>
        <Text style={styles.title}>{shopName || 'Medical Shop'} - Dashboard Report</Text>
        <Text style={styles.subtitle}>Generated on {format(new Date(), 'PPP p')}</Text>
      </View>

      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Today's Summary</Text>
        <View style={styles.statsGrid}>
          <View style={styles.statCard}>
            <Text style={styles.statLabel}>Total Sales</Text>
            <Text style={styles.statValue}>{stats.todaySales}</Text>
          </View>
          <View style={styles.statCard}>
            <Text style={styles.statLabel}>Revenue</Text>
            <Text style={styles.statValue}>₹{stats.todayRevenue.toLocaleString()}</Text>
          </View>
          <View style={styles.statCard}>
            <Text style={styles.statLabel}>Low Stock Items</Text>
            <Text style={styles.statValue}>{stats.lowStockItems}</Text>
          </View>
          <View style={styles.statCard}>
            <Text style={styles.statLabel}>Expiring Soon</Text>
            <Text style={styles.statValue}>{stats.expiringItems}</Text>
          </View>
        </View>
      </View>

      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Recent Sales</Text>
        <View style={styles.table}>
          <View style={styles.tableHeader}>
            <Text style={[styles.tableCell, { color: 'white' }]}>Invoice</Text>
            <Text style={[styles.tableCell, { color: 'white' }]}>Patient</Text>
            <Text style={[styles.tableCell, { color: 'white' }]}>Amount</Text>
            <Text style={[styles.tableCell, { color: 'white' }]}>Date</Text>
          </View>
          {recentSales.slice(0, 10).map((sale, index) => (
            <View key={index} style={styles.tableRow}>
              <Text style={styles.tableCell}>{sale.invoice_number || '-'}</Text>
              <Text style={styles.tableCell}>{sale.patient_name}</Text>
              <Text style={styles.tableCell}>₹{sale.total.toFixed(2)}</Text>
              <Text style={styles.tableCell}>{format(new Date(sale.created_at), 'dd/MM/yy')}</Text>
            </View>
          ))}
        </View>
      </View>

      <Text style={styles.footer}>
        This report was automatically generated by {shopName || 'Medical Shop'} Management System
      </Text>
    </Page>
  </Document>
);

export const DashboardPDFDownload = ({ stats, recentSales, shopName }: DashboardPDFProps) => {
  return (
    <PDFDownloadLink
      document={<DashboardDocument stats={stats} recentSales={recentSales} shopName={shopName} />}
      fileName={`dashboard-report-${format(new Date(), 'yyyy-MM-dd')}.pdf`}
    >
      {({ loading }) => (
        <Button variant="outline" disabled={loading}>
          <Download className="w-4 h-4 mr-2" />
          {loading ? 'Generating...' : 'Download Report'}
        </Button>
      )}
    </PDFDownloadLink>
  );
};
